version: '3.6'
services:
  server:
    image: stephenj:lattest
    build: .
    container_name: stephenj1
  proxy:
    image: nginx
    container_name: stephenj2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:8080